repo: "hide-show-responsively"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - css
  - img-block-100
  - responsive-css
  - screenshots-all

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    has:
      - ['.dino-wrap']
      - ['@25em', '.dino']
      - ['@38em', '.dino']
      - ['@60em', '.dino']
    search:
      - 'display: none'
